name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image for tests
        run: docker build --target test --tag todo-app:test .
      - name: Run tests from docker image
        run: docker run todo-app:test 
  
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/module-8'
    steps:
      - uses: actions/checkout@v2
      - name: Log into dockerhun
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u schandarana --password-stdin
      - name: Build production image
        run: docker build --target production --tag schandarana/todo-app:$GITHUB_SHA --tag schandarana/todo-app:latest .
      - name: Push image to dockerhub
        run: docker push schandarana/todo-app --all-tags
      - name: Update image tag 
        run: docker tag schandarana/todo-app:latest registry.heroku.com/shiv-devops-course-starter/web
      - name: Login to heroku container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: push image to heroku
        run: docker push registry.heroku.com/shiv-devops-course-starter/web
      - name: release heroku app
        run: heroku container:release web -a shiv-devops-course-starter

