name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image for tests
        run: docker build --target test --tag todo-app:test .
      - name: Run tests from docker image
        run: docker run todo-app:test 
  
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Log into dockerhub
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u schandarana --password-stdin
      - name: Build production image
        run: docker build --target production --tag schandarana/todo-app:$GITHUB_SHA --tag schandarana/todo-app:latest .
      - name: Push image to dockerhub
        run: docker push schandarana/todo-app --all-tags

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to azure
        run: curl -dH -X POST https://\$${{ secrets.AZURE_WEBHOOK_DETAILS }}.scm.azurewebsites.net/api/registry/webhook